version: "3"
services:
  hub:
    image: selenium/hub:3.14
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.14
    shm_size: '128m'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  search-module:
    image: murthyb/selenium-docker
    depends_on:
      - chrome
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - MODULE=search-module.xml
    volumes:
      - C:/MyWk/IntelliJWK/target/searchModule:/usr/share/seleniumdocker/test-output
  book-flight-module:
    image: murthyb/selenium-docker
    depends_on:
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - MODULE=book-flight-module.xml
    volumes:
      - C:/MyWk/IntelliJWK/target/bookflightModule:/usr/share/seleniumdocker/test-output